# Site settings
title: min020's blog
motto: "과제 기록용"
email: kimmin020@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://min020.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  min020

# Build settings
markdown: kramdown
